services:
  homeassistant:
    container_name: ha-denkovi-dev
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ../custom_components/denkovi_smartden:/config/custom_components/denkovi_smartden
    environment:
      - TZ=Europe/Brussels
